### ISSUE TITLE
[Request] Context manager class to manage files.

### ISSUE THREAD

**Issue by dach19** [Isaac95Mendez/Test-Automation-AMX#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Isaac95Mendez** [comment]
En que clase se tiene que hacer este cambio y cual es el cambio?

**Comment by dach19** [comment]
Está relacionado con el PR de abrir y cerrar archivos.
De preferencia para la manipulación de archivos usa `with file open as f:`

Dependiendo de las operaciones a realizar se puede implementar una clase.

http://book.pythontips.com/en/latest/context_managers.html

**Comment by Isaac95Mendez** [comment]
Se creó la clase para administrar archivos y se usará with file open as f: para la manipulación de archivos
