### ISSUE TITLE
[Blocker] Facebook Login

### ISSUE THREAD

**Issue by Isaac95Mendez** [Isaac95Mendez/Test-Automation-AMX#15]
**Is your feature request related to a problem? Please describe.**
Uiautomator does not show the elements inside screen on the Facebook app in the login section.

**Describe the solution you'd like**
Be able to select the elements inside the login screen in the Facebook app

**Describe alternatives you've considered**
Use another apps to test the login section.

**Additional context**
It can be related with security reasons.

**Comment by Isaac95Mendez** [comment]
We are going to use a workaround.
The solution is to open the Facebook application with a logged user.

**Comment by dach19** [comment]
A workaround is not a Solution.

**Comment by Isaac95Mendez** [comment]
> A workaround is not a Solution.

It will be a temporary solution until we can solve the problem with the Facebook login

**Comment by dach19** [comment]
Puedes intentar con este script.

`from uiautomator import Device
import time


def main():

    username = "name@email.com"
    password = "secret123"

    d = Device("E1MGA2E820112549")
    d(className="android.view.ViewGroup").click()
    time.sleep(1)
    usr = d(text="Phone or Email")
    pw = d(text="Password")

    usr.set_text(username)
    pw.set_text(password)

    d.press.enter()

main()`

**Comment by Isaac95Mendez** [comment]
> Puedes intentar con este script.
> 
> `from uiautomator import Device
> import time
> 
> def main():
> 
> ```
> username = "name@email.com"
> password = "secret123"
> 
> d = Device("E1MGA2E820112549")
> d(className="android.view.ViewGroup").click()
> time.sleep(1)
> usr = d(text="Phone or Email")
> pw = d(text="Password")
> 
> usr.set_text(username)
> pw.set_text(password)
> 
> d.press.enter()
> ```
> main()`

Muchas gracias, este código funciona. Se puede agregar el proyecto en el próximo sprint.

**Comment by dach19** [comment]
Excelente! Buen trabajo. 👍

**Comment by Isaac95Mendez** [comment]
Pull request
https://github.com/Isaac95Mendez/Test-Automation-AMX/pull/50
