### ISSUE TITLE
Error in Windows console: module not found

### ISSUE THREAD

**Issue by Isaac95Mendez** [Isaac95Mendez/Test-Automation-AMX#46]
**Describe the bug**
When you run the program on the windows console the program does not find the modules.

**To Reproduce**
1. Clone the project in your computer 
2. Open CMD and got to the project folder
3. Execute MyDevice.py
4. See error in the console

**Expected behavior**
Execute one of the methods of the class successfully

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Isaac95Mendez** [comment]
@dach19

**Comment by dach19** [comment]
Ok! lo reviso.

**Comment by dach19** [comment]
Podrían ayudarme a realizar un experimento por favor.
Sobre la raíz del repo crear un ambiente virtual
`python -m virtualenv AMX-env`

Activarlo
`source AMX-env/bin/activate`
`pip install -r requirements.txt`

Intentar correr pruebas, y si funcionan los imports.

**Comment by Isaac95Mendez** [comment]
Gracias, ya funcionan los imports en cmd.
