### ISSUE TITLE
[Request] Update MyDevice class to inherit from Device

### ISSUE THREAD

**Issue by dach19** [Isaac95Mendez/Test-Automation-AMX#51]
**Is your feature request related to a problem? Please describe.**
Improve performance.

**Describe the solution you'd like**
`
class MyDevice(Device):`
`    def __init__(self, device_id):`
`        super(MyDevice, self).__init__(device_i)
`

**Describe alternatives you've considered**

**Additional context**

**Comment by Isaac95Mendez** [comment]
Listo

**Comment by Isaac95Mendez** [comment]
#50
